### ISSUE TITLE
TIPC运行异常

### ISSUE THREAD

**Issue by jerrywgz** [FL77N/Fast-RCNN-on-PPDet#1]
1. tipc运行文档中存在test_tipc2这个错误路径
2. deploy/python/infer.py 文件内容异常

**Comment by FL77N** [comment]
> 1. tipc运行文档中存在test_tipc2这个错误路径
> 2. deploy/python/infer.py 文件内容异常

你好!
->1、文档问题已经进行修复。
->2、内容异常具体是指的什么呢？因为我对 PPDet 进行了一定程度的修改

**Comment by jerrywgz** [comment]
已线下沟通修复
